import os
import re

# set the directory containing the files to search
dir_path = r"C:\DIGITs\xmlfileswithlocations"

locations = ['Princess Kashmir',
    'East',
    'Agnes',
    'Neptune',
    'Jupiter',
    'Earth',
    'The Springfield Mall',
    'North Kilttown',
    'Saturn',
    "Mother Earth's",
    'earth',
    'South',
    'Dumbville',
    'Mother Earth',
    'Europe',
    'Hard Rock',
    'Lake Titicaca',
    'Mount Everest',
    'Maui',
    'East St. Louis',
    'Baltic Avenue',
    'The Springfield Excitement',
    'Territory',
    'Helena',
    'The North Pole',
    'The South Seas',
    'The Emerald Isle',
    'Africa',
    'New England',
    'The Crab Nebula',
    'Mars',
    'Highlands',
    'Midwest',
    'Peak',
    'Pacific',
    'Odyssey',
    'Eastern Europe',
    'Toluca Lake',
    'Roman Easter',
    'Heights',
    'Mount Splashmore',
    "Moe's Tavern",
    'Kwik',
    'C.I.A.',
    'the Sapphire Lounge',
    'the Nuclear Power Plant',
    'the Springfield Elementary School',
    'Barn',
    'Valve Maintenance',
    "Santa's Little Helper",
    'Springfield Downs',
    'Party',
    'Motel',
    'Albanian Airlines',
    'the Springfield State Prison',
    'Vassar',
    'Family Therapy Center',
    'The Springfield Retirement Home',
    'Big Dipper',
    'the North Star',
    'the "International House of Answering Machines"',
    'the Jerky Hut',
    'City Hall',
    'the Statue of Liberty',
    'Lullaby',
    'the Springfield Mall',
    'the Fiesta Terrace',
    'the Ye Old Ramp Inn',
    'the Monty Burns Casino',
    'the Springfield Drive-In',
    'Road King',
    'Evergreen Terrace',
    'Pro Player Stadium',
    'Disneyland',
    'the White House',
    'the Grand Concourse',
    'Highway 7',
    'the Garden of Eden',
    'Bird Squawks',
    'Pearl Harbor',
    "the Loch Ness Monster",
    "Loch Ness High School's",
    'the Municipal Fortress of Vengeance',
    'the Chuck Garabedian Mega-Savings Seminar',
    'the Town Homes',
    'Sterling Point',
    'the Shelbyville Bird Sanctuary',
    'the Chrysler Building',
    'Notre Dame',
    'Woosterfield Arena',
    'the rec center',
    'Winter Palace',
    'the Washington Monument',
    'Waverly Elementary',
    'Springfield Elementary',
    "Lover's Lagoon",
    'Airport Hotel',
    'Broadway',
    'the Kennedy Center Honors',
    'The Hall of Vice Presidents',
    "MacDill Air Force Base",
    "Superman's Fortress of Solitude",
    'Main Street',
    'Fort Dix',
    'the Shelbyville Mall',
    'Springfield',
    'Mud City',
    'Bethlehem',
    'Elf County',
    'Tirana',
    'Albania',
    'France',
    'Yucatan',
    'Offramp',
    'America',
    'Santa Fe',
    'Tucson',
    'Phoenix',
    'El Paso',
    'Albuquerque',
    'Burns Manor',
    'Toledo',
    'Brunswick',
    'Malibu', 'North Kilt', 'Menlo Park', 'Washington', 'L.A.', 'Hollywood', 'Bethesda',    'Philly', 'Concord', 'Hard Rock', 'Vietnam', 'Woodstock', 'Maine',    'Canada', 'Las Vegas', 'Chicago', 'Alabama', 'Miami', 'Murray Hill',    'Quebec', 'Albany', 'Yemen', 'Atlanta', 'Egypt', 'Venice', 'Arizona',    'St. Nick', 'California', 'Kyoto', 'Reichstag', 'England', 'Poland',    'Paris', 'Budapest', 'Moscow', 'Queens', 'Pennsylvania', 'Detroit',    'Shelbyville', 'Hokkaido', 'Sarajevo', 'Germany', 'Mongolia', 'Cleveland',    'Buenos Aires', 'Bangkok', 'Russia', 'Montreal', 'PA', 'conga', 'Radiola',    'Monsterometer', 'Hawaii', 'Popping', 'Houston', 'Hartford', 'Connecticut',    'Athens', 'Kabuki', 'The United States', 'Nantucket', 'Cayman', 'Jamaica',    'Transylvania', 'Tokyo', 'Japan', 'Americatown', 'U.S.A.', 'Babylon', 'the Bartish Empire', 'Diego', 'Boston', 'Tunisia', 'New York']

# construct the regex pattern to match any of the names
pattern = r"\b(" + "|".join(locations) + r")\b"

# loop through each file in the directory and replace the names
for filename in os.listdir(dir_path):
    if filename.endswith(".xml"):
        with open(os.path.join(dir_path, filename), "r", encoding="utf8") as file:
            text = file.read()
            replaced_text = re.sub(pattern, r"<location>\g<0></location>", text, flags=re.IGNORECASE)
        with open(os.path.join(dir_path, filename), "w", encoding="utf8") as file:
            file.write(replaced_text)


